In [16]:
import pandas as pd

In [17]:
# Load csv
heart_data = pd.read_csv('../../data/heart_clean.csv')

In [18]:
heart_data.head()

,age,sex,cp,chol,restecg,exang,oldpeak,slope,thal,target,restingBP,fastingBS,maxHR,numVessels
0,63,1,3,233,0,0,2.3,0,1,1,145,1,150,0
1,37,1,2,250,1,0,3.5,0,2,1,130,0,187,0
2,41,0,1,204,0,0,1.4,2,2,1,130,0,172,0
3,56,1,1,236,1,0,0.8,2,2,1,120,0,178,0
4,57,0,0,354,1,1,0.6,2,2,1,120,0,163,0

In [19]:
# Drop unnecessary columns
heart_data.drop(['numVessels', 'thal'], inplace=True, axis=1)
heart_data.head()

,age,sex,cp,chol,restecg,exang,oldpeak,slope,target,restingBP,fastingBS,maxHR
0,63,1,3,233,0,0,2.3,0,1,145,1,150
1,37,1,2,250,1,0,3.5,0,1,130,0,187
2,41,0,1,204,0,0,1.4,2,1,130,0,172
3,56,1,1,236,1,0,0.8,2,1,120,0,178
4,57,0,0,354,1,1,0.6,2,1,120,0,163

In [7]:
# Write the preprocessed data as a csv file
heart_data.to_csv('../../data/heart_data_preprocessed.csv', index=False)